services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - .docker/redis/data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  api:
    container_name: poc_websocket_api
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      redis:
        condition: service_healthy
