apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodeserver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodeserver
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
